services:
  db:
    image: mysql:5.7.44
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - '8001:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
    restart: always
  backend:
    # image: backend
    build:
      args:
        - NODE_ENV=development
      context: ./server
    ports:
      - '3000:3000'
    volumes:
      - ./server:/code
      - ./server/package.json:/code/package.json
      # - ./server/.env:/code/.env:rw
      - /code/node_modules
      - ./wait-for-mysql.sh:/wait-for-mysql.sh
    environment:
      - DB_HOST=db
    command: sh /wait-for-mysql.sh npm run start-dev
    depends_on:
    - db
  phpmyadmin:
    image: phpmyadmin:5.2.1
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db
  frontend:
    build:
      args:
        - NODE_ENV=development
      context: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
    - "5173:5173"
    command: npm run dev -- --host
    environment:
      - VITE_APP_API_URL=http://localhost:3000/
    depends_on:
    - backend
volumes:
  database: